
version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - mkdir -p gen/go
      - protoc -I proto proto/sso/sso.proto 
        --go_out=./gen/go 
        --go_opt=paths=source_relative 
        --go-grpc_out=./gen/go/ 
        --go-grpc_opt=paths=source_relative


# для запуска: task generate
# проверка

